{% set version = "8.9.1.23" %}
{% set cuda_major = (cuda_compiler_version|default("12.0.0")).split(".")[0] %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: cudnn
  version: {{ version }}

source:
  # Hard-code `cuda_major` in the URLs as the bot can't parse it
  url: https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/{{ platform }}/cudnn-{{ platform }}-{{ version }}_cuda11-archive.{{ extension }}  # [cuda_major == "11"]
  url: https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/{{ platform }}/cudnn-{{ platform }}-{{ version }}_cuda12-archive.{{ extension }}  # [cuda_major == "12"]
  sha256: a6d9887267e28590c9db95ce65cbe96a668df0352338b7d337e0532ded33485c  # [linux64 and cuda_major == "11"]
  sha256: 35163c5c542be0c511738b27e25235193cbeedc5e0e006e44b1cdeaf1922e83e  # [linux64 and cuda_major == "12"]
  sha256: 0a61fae873a046a0a86b2e6d8cdb039da155bc2fcfa215acef6fc61ce618cb2f  # [aarch64 and cuda_major == "11"]
  sha256: 823e0e2e19849cf645500d1239b8bd7e7aa1f21d5c98309eada363f943e2f486  # [aarch64 and cuda_major == "12"]
  sha256: aaa5582ba9951c3645b103abe08a0b8b046da2b277b2c1d696216f3392225394  # [ppc64le and cuda_major == "11"]
  sha256: 8dc6e639688979f5cc424560f06e41aed26199396c905db22151dbf81314f559  # [ppc64le and cuda_major == "12"]
  sha256: 5a1522fd8351f2c00f0afc12bb6970458d1ba171f11c9cb483fb7f281e7dea1a  # [win and cuda_major == "11"]
  sha256: 474c75d809e15d023de83e96715dce28ccfba19cdf43c47377ae80384ff96c96  # [win and cuda_major == "12"]

build:
  number: 0
  skip: True  # [osx]
  skip: True  # [cuda_compiler_version == "11.2"]
  # Disable binary relocation to workaround patchelf issue
  # xref: https://github.com/NixOS/patchelf/issues/492
  binary_relocation: false
  script:
    - mkdir -p $PREFIX/include               # [linux]
    - cp include/cudnn*.h $PREFIX/include/   # [linux]
    - mkdir -p $PREFIX/lib                   # [linux]
    - mv lib/libcudnn*.so* $PREFIX/lib/      # [linux]

    - mkdir %LIBRARY_INC%                                   # [win]
    - copy %SRC_DIR%\\include\\cudnn*.h %LIBRARY_INC%\\     # [win]
    - mkdir %LIBRARY_LIB%                                   # [win]
    - copy %SRC_DIR%\\lib\\x64\\cudnn*.lib %LIBRARY_LIB%\\  # [win]
    - mkdir %LIBRARY_BIN%                                   # [win]
    - copy %SRC_DIR%\\bin\\cudnn*.dll %LIBRARY_BIN%\\       # [win]
  ignore_run_exports:
    - cudatoolkit
  run_exports:
    - {{ pin_subpackage('cudnn') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - sysroot_{{ target_platform }} 2.17  # [linux]
  host:
    - cuda-version {{ cuda_major }}.0
    - patchelf >=0.12  # [linux]
    # to suppress ".so not found" errors
    - libzlib       # [linux]
    - libzlib-wapi  # [win64]
  run:
    - {{ pin_compatible("cuda-version", max_pin="x") }}
    {% if cuda_major == "11" %}
    - cudatoolkit 11.*
    {% else %}
    - cuda-nvrtc
    - libcublas
    {% endif %}
  run_constrained:
    - __glibc >=2.17                        # [linux and not aarch64]
    - __glibc >=2.28                        # [linux and aarch64]
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  requires:
    - {{ compiler('c') }}  # [linux]
  files:
    - test_load_elf.c      # [linux]
  commands:
    - if not exist %LIBRARY_INC%/cudnn.h exit 1                       # [win]
    - if not exist %LIBRARY_INC%/cudnn_adv_train.h exit 1             # [win]
    - if not exist %LIBRARY_LIB%/cudnn.lib exit 1                     # [win]
    - if not exist %LIBRARY_LIB%/cudnn_adv_train.lib exit 1           # [win]
    - if not exist %LIBRARY_BIN%/cudnn64_8.dll exit 1                 # [win]
    - if not exist %LIBRARY_BIN%/cudnn_adv_train64_8.dll exit 1       # [win]
    - test -f $PREFIX/include/cudnn.h                                 # [linux]
    - test -f $PREFIX/include/cudnn_adv_train.h                       # [linux]
    - test -f $PREFIX/lib/libcudnn.so                                 # [linux]
    - test -f $PREFIX/lib/libcudnn_adv_train.so                       # [linux]
    - ${GCC} test_load_elf.c -std=c99 -Werror -ldl -o test_load_elf   # [linux]
    - for f in $PREFIX/lib/libcudnn*.so; do ./test_load_elf $f; done  # [linux]

about:
  home: https://developer.nvidia.com/cudnn
  license: LicenseRef-cuDNN-Software-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/deeplearning/cudnn/sla/index.html
  summary: "NVIDIA's cuDNN deep neural network acceleration library"
  description: |
    NVIDIA CUDA Deep Neural Network (cuDNN) is a GPU-accelerated library of
    primitives for deep neural networks. It provides highly tuned
    implementations of routines arising frequently in DNN applications.

    License Agreements:- The packages are governed by the NVIDIA cuDNN
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA cuDNN EULA -
    https://docs.nvidia.com/deeplearning/cudnn/sla/index.html
  doc_url: https://docs.nvidia.com/deeplearning/cudnn/
  dev_url: https://developer.nvidia.com/rdp/cudnn-download

extra:
  recipe-maintainers:
    - adibbley
    - bdice
    - jakirkham
    - vyasr
